<?php ?>
<script>
    require(['jquery', 'prototype'], function(jQuery){
        window.mondidoToggleSolution = function (id, url) {
            var doScroll = false;
            Fieldset.toggleCollapse(id, url);
            if ($(this).hasClassName("open")) {
                $$(".with-button button.button").each(function(anotherButton) {
                    if (anotherButton != this && $(anotherButton).hasClassName("open")) {
                        $(anotherButton).click();
                        doScroll = true;
                    }
                }.bind(this));
            }
            if (doScroll) {
                var pos = Element.cumulativeOffset($(this));
                window.scrollTo(pos[0], pos[1] - 45);
            }
        }
    });
</script>
